trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

env:
- ARM_CLIENT_ID: $(ARM_CLIENT_ID)
- ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
- ARM_TENANT_ID: $(ARM_TENANT_ID)
- ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
- TF_VAR_imagebuild: $(tag)

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: self
    variables: 
    - group: TerraformEnvVars
    
    
# pool:
#   name: self
    steps:
      

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
      displayName: 'Terraform : init'
      inputs:
        backendServiceArm: synapse
        backendAzureRmResourceGroupName: 'tf-rg'
        backendAzureRmStorageAccountName: tfstorage123
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: synapse.tfstate

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
      displayName: 'Terraform : plan'
      inputs:
        command: plan
        environmentServiceNameAzureRM: synapse

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2
      displayName: 'Terraform : validate and apply'
      inputs:
        command: apply
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: synapse

